export const ADD_BOOK_LOADING = "ADD_BOOK_LOADING";
export const ADD_BOOK_FAILURE = "ADD_BOOK_FAILURE";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";

export const GET_ALL_BOOKS_LOADING = "GET_ALL_BOOKS_LOADING";
export const GET_ALL_BOOKS_FAILURE = "GET_ALL_BOOKS_FAILURE";
export const GET_ALL_BOOKS_SUCCESS = "GET_ALL_BOOKS_SUCCESS";

export const GET_BOOK_BY_ID_LOADING = "GET_BOOK_BY_ID_LOADING";
export const GET_BOOK_BY_ID_FAILURE = "GET_BOOK_BY_ID_FAILURE";
export const GET_BOOK_BY_ID_SUCCESS = "GET_BOOK_BY_ID_SUCCESS";

export const EDIT_BOOK_LOADING = "EDIT_BOOK_LOADING";
export const EDIT_BOOK_FAILURE = "EDIT_BOOK_FAILURE";
export const EDIT_BOOK_SUCCESS = "EDIT_BOOK_SUCCESS";

export const DELETE_BOOK_LOADING = "DELETE_BOOK_LOADING";
export const DELETE_BOOK_FAILURE = "DELETE_BOOK_FAILURE";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";